### PR TITLE
Document installation without existing Java

### PR DESCRIPTION
**Pull request by Jaakkonen**

### CODE REVIEW

**Comment by dongjinleekr** [comment]
Hi @Jaakkonen,

Thank you for opening the first PR. :congratulations: Your point is right, so I just filed the issue as #3. Since I added some documentation on `README.md`, merging after the rebasing would be good.

Before we go further, I have a question; could you please explain a little bit about where the dependency on `libnspr4` and `libsqlite3-0` came? I inspected the dependency tree but could find `libnss3` only.

**Comment by Jaakkonen** [comment]
The `libnspr4` and `libsqlite3-0` are `libnss3` dependencies (see package in Debian Buster: https://packages.debian.org/bullseye/libnss3). When a package is in unconfigured state with missing dependencies you need to explicitly declare all packages that are going to be installed such that the end state is installation with no missing dependencies. Thus it needs the `libnss3` dependencies listed there too. Another option is to use `--fix-missing` option on `apt` which enables dependency resolving when the starting state has unconfigured packages.

I rebased my fork so that this should be merge-able.

**Comment by dongjinleekr** [comment]
Great! LGTM. :smiley:

**Comment by dongjinleekr** [comment]
@Jaakkonen Congratulations, this is the first merged contribution to the repo! :+1: :+1: :+1:

**Pull request merged**
